<?php
	session_start();
	if(isset($_SESSION['user_id']))
	{
		unset($_SESSION['user_id']);
		unset($_SESSION['user_name']);
		//session_unset($_SESSION['password']);
		header("location:../index.php");
	}
?>